version: '3.7'
services:
  app:
    container_name: online-shopping
    image: online-shopping
    ports:
      - 8080:8080
    depends_on:
      - postgresqldb
    links:
      - postgresqldb:postgres
  postgresqldb:
    image: "postgres:latest"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
    